### PR TITLE
Update OpenSCAD to 2019.05

### LINKED ISSUE #4: Update to 2019.05

### PR DESCRIPTION
**Pull request by goncalossilva**
This PR updates OpenSCAD to 2019.05. I've tested and updated the build config so that it builds successfully for the newer version, but have not tested the app itself (ie. ran [all steps](http://docs.flatpak.org/en/latest/first-build.html) up to number 4, inclusive). I am inexperienced with flatpak and unsure how to handle step 5 for OpenSCAD specifically. Building works, and hopefully this PR makes it easier to update to the new version.

Closes #4.

### CODE REVIEW

**Comment by goncalossilva** [comment]
I have disabled unsupported architectures in the last commit. I am unsure how to handle the remaining problem. In sum, OpenSCAD's icon is 688x688 and it is expected to be 512x512 [when moved](https://github.com/flathub/org.openscad.OpenSCAD/blob/master/org.openscad.OpenSCAD.json#L167).

It could make sense to have imagemagick as a build time dependency to resize this, but I am unsure about the best way to do that. The "modules" key lists out run time dependencies. Is there a similar entry for build time dependencies?

**Comment by goncalossilva** [comment]
Icon is handled, but now appstream verification fails and I am way out of my comfort zone. I hope the remaining work is helpful. :+1:

**Comment by tpimh** [comment]
I have built and tested it locally, everything works as expected. No idea why did it fail the checks.

**Comment by goncalossilva** [comment]
Closing in favor of #6

**Pull request closed without merging**
